### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hi-ogawa** [hi-ogawa/web-audio-worklet-rust#4]
- [x] keyboard shortcut
  - https://github.com/hi-ogawa/web-audio-worklet-rust/pull/5
- [x] unit test wasm (on nodejs)
  - https://github.com/hi-ogawa/web-audio-worklet-rust/pull/6
- [x] comlink to simplify `AudioWorkletProcessor` RPC
  - https://github.com/hi-ogawa/web-audio-worklet-rust/pull/6
- [x] ability to select/download soundfont
  - https://github.com/hi-ogawa/web-audio-worklet-rust/pull/6
- [x] maybe sound is not getting stereo?
- [x] highlight keys on hover/play
  - https://github.com/hi-ogawa/web-audio-worklet-rust/pull/7
- [ ] ability to change fluidsynth settings (gain, chorus, reverb, etc...)
- [ ] persist selected soundfont/instrument
- [ ] auto load `FluidR3_GM.sf2`
- [ ] move keyboard shortcut octave
- [ ] tweak key geometry (width/height)
- [ ] audio meter
- [ ] input via web midi API
- [ ] refactor audio system management (maybe separate it from UI to be singleton?)
- [x] automatic typing export (currently manual written due to https://github.com/rustwasm/wasm-bindgen/issues/111)
  - https://github.com/GREsau/schemars
  - https://github.com/bcherny/json-schema-to-typescript
  - https://github.com/tcr/wasm-typescript-definition
  - https://github.com/hi-ogawa/web-audio-worklet-rust/pull/8
- [x] refactor wasm-bindgen to js interface https://github.com/hi-ogawa/web-audio-worklet-rust/pull/9

---

- [x] perf

https://github.com/hi-ogawa/web-audio-worklet-rust/blob/fd0e18b917acc72ea03f671b3277f8486188f48e/packages/app/src/audio-worklet/soundfont-processor.ts#L13-L15

**Comment by hi-ogawa** [comment]
## UI ideas

- Nob UI cannot work on touch? Fader UI might be more universal.

## references

- lmms

![image](https://user-images.githubusercontent.com/4232207/211137269-b3150e9c-f7f9-4c69-9e1d-be11ee63ac9e.png)


- calf

![image](https://user-images.githubusercontent.com/4232207/211137610-a797593e-711f-4c25-a7d1-509a074f64b2.png)

- qsynth

https://qsynth.sourceforge.io/
